name: Test VSCode extension

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node:
          - 19
    steps:
      - name: Set autocrlf to false
        run: git config --global core.autocrlf false
        if: ${{ success() && matrix.os == 'windows-latest' }}
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Node ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: yarn install --immutable --immutable-cache --check-cache
      - name: Run test
        # pretest run compile and lint automatically
        run: yarn test
